name: Add contributors
on:
  # schedule:
  #   - cron: '5 * * * *'
  push:
    branches:
      - fix/ci-contributor

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: BobAnkh/add-contributors@master
        with:
          REPO_NAME: "alibaba/ice"
          CONTRIBUTOR: "## Contributors"
          COLUMN_PER_ROW: "10"
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH: ‘’
          PULL_REQUEST: 'master'
          IMG_WIDTH: "60"
          FONT_SIZE: "14"
          PATH: "/README.md"
          COMMIT_MESSAGE: "docs(README): update contributors"
          AVATAR_SHAPE: "round"
